# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataquery_form.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(969, 573)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_IPAddress = QtWidgets.QLineEdit(Form)
        self.lineEdit_IPAddress.setObjectName("lineEdit_IPAddress")
        self.horizontalLayout_3.addWidget(self.lineEdit_IPAddress)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_Port = QtWidgets.QLineEdit(Form)
        self.lineEdit_Port.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_Port.setObjectName("lineEdit_Port")
        self.horizontalLayout_3.addWidget(self.lineEdit_Port)
        self.pushButton_update = QtWidgets.QPushButton(Form)
        self.pushButton_update.setObjectName("pushButton_update")
        self.horizontalLayout_3.addWidget(self.pushButton_update)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_CompanyName = QtWidgets.QLineEdit(Form)
        self.lineEdit_CompanyName.setObjectName("lineEdit_CompanyName")
        self.horizontalLayout.addWidget(self.lineEdit_CompanyName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_KeyDog = QtWidgets.QLineEdit(Form)
        self.lineEdit_KeyDog.setObjectName("lineEdit_KeyDog")
        self.horizontalLayout_2.addWidget(self.lineEdit_KeyDog)
        self.pushButton_register = QtWidgets.QPushButton(Form)
        self.pushButton_register.setObjectName("pushButton_register")
        self.horizontalLayout_2.addWidget(self.pushButton_register)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lineEdit_ServerName = QtWidgets.QLineEdit(Form)
        self.lineEdit_ServerName.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_ServerName.setObjectName("lineEdit_ServerName")
        self.horizontalLayout_5.addWidget(self.lineEdit_ServerName)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.lineEdit_DataBase = QtWidgets.QLineEdit(Form)
        self.lineEdit_DataBase.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_DataBase.setObjectName("lineEdit_DataBase")
        self.horizontalLayout_7.addWidget(self.lineEdit_DataBase)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.lineEdit_LoginID = QtWidgets.QLineEdit(Form)
        self.lineEdit_LoginID.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_LoginID.setObjectName("lineEdit_LoginID")
        self.horizontalLayout_6.addWidget(self.lineEdit_LoginID)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEdit_LoginPwd = QtWidgets.QLineEdit(Form)
        self.lineEdit_LoginPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_LoginPwd.setObjectName("lineEdit_LoginPwd")
        self.horizontalLayout_4.addWidget(self.lineEdit_LoginPwd)
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_4.addWidget(self.pushButton_save)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.textEdit_log = QtWidgets.QTextEdit(Form)
        self.textEdit_log.setObjectName("textEdit_log")
        self.verticalLayout_2.addWidget(self.textEdit_log)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        self.pushButton_update.clicked.connect(Form.updateip)
        self.pushButton_register.clicked.connect(Form.register)
        self.pushButton_save.clicked.connect(Form.saveset)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Internet IP"))
        self.label_4.setText(_translate("Form", "Port"))
        self.lineEdit_Port.setText(_translate("Form", "1508"))
        self.pushButton_update.setText(_translate("Form", "Update"))
        self.label.setText(_translate("Form", "Company Name"))
        self.label_2.setText(_translate("Form", "KeyDog"))
        self.pushButton_register.setText(_translate("Form", "Register"))
        self.label_6.setText(_translate("Form", "ServerName"))
        self.label_8.setText(_translate("Form", "Database"))
        self.label_7.setText(_translate("Form", "Login ID"))
        self.label_5.setText(_translate("Form", "Login Pwd"))
        self.pushButton_save.setText(_translate("Form", "save"))

